### ISSUE TITLE
Добавить мануал по составлению и отправке годовой подоходной декларации

### ISSUE THREAD

**Issue by sergeyklay** [sobolevbel/jdg#103]
Думаю в конце года эта тема будет особенно актуальна. Так или иначе, у новичков с этим точно проблемы. Было бы не плохо добавить пошаговую инструкцию сюда /jdg/declarations

**Comment by iamtodor** [comment]
и упомянуть, что 1% мы законно имеем право отправить на благотворительность

**Comment by sobolevbel** [comment]
Да, это есть в планах. Думаю, ближе к концу года напишу как сам буду составлять.
