### ISSUE TITLE
ZUS: składki na ubezpieczenia społeczne

### ISSUE THREAD

**Issue by iamtodor** [sobolevbel/jdg#125]
В дополнении к
- https://github.com/sobolevbel/jdg/pull/122
- https://github.com/sobolevbel/jdg/pull/123
- https://github.com/sobolevbel/jdg/pull/124

возможно, еще следует дописать, что 

```
Если ты переходишь порог 300 тыс то зус уже 1007.81, к ней по окончанию ульги на старт добавляется спулечна 285.71, и конечная сумма будет 1293.52
```

Взято отсюда https://www.zus.pl/baza-wiedzy/skladki-wskazniki-odsetki/skladki/wysokosc-skladek-na-ubezpieczenia-spoleczne

**Comment by pointless-henry** [comment]
в этом коммите https://github.com/sobolevbel/jdg/commit/7cf559539646241ce205219203feac2d4cb97b65#diff-692fd1355c9d1d4f96fe83244f6102c918f068a452966c8574dabea3db9e4785R147 была добавлена строка "Вместе (A + B + C):" в таблицу на [странице про ZUS](https://sobolevbel.github.io/jdg/zus/).
@iamtodor, можно закрыть тикет #125 как выполненный?

**Comment by iamtodor** [comment]
@pointless-henry ага, спасибо!
