### ISSUE TITLE
Add information about ZUS vacation tax relief

### ISSUE THREAD

**Issue by zarypov** [sobolevbel/jdg#189]
https://www.zus.pl/-/wakacje-sk%C5%82adkowe-zwolnienie-z-op%C5%82acania-sk%C5%82adek-zus

**Comment by zarypov** [comment]
I am going to take this one

**Comment by zarypov** [comment]
PR merged
I assume issue either can stay open until the procedure is verified by someone, or can be closed and fixes to text will be introduced separately if needed.

**Comment by iamtodor** [comment]
Closed by https://github.com/sobolevbel/jdg/pull/190
